### ISSUE TITLE
jquery-expander has glitchy behavior

### ISSUE THREAD

**Issue by bepetersn** [sc3/crime-punishment#137]
The whole expandable section appears to jump up and down very briefly, and then a fadeIn effect makes the section expand below the visible part of the page. Sometimes, this seems to result in the mouse/ viewport shifting to somewhere other than where it was. Most of the time, you have to scroll down before you can then close the expandable section (like if it was bigger than you maybe expected).

I would like to have a more reliable option for this behavior, maybe eventually. I guess it serves its purpose for now.

**Comment by bepetersn** [comment]
One thing that might make it slightly less glitchy is choosing a different animation than default. Maybe something really simple, or no animation. Possibly could help.

**Comment by eads** [comment]
I noticed this too.

Please just drop the expander. If the client has a problem, I'll talk with
them about it.

On Wed, Mar 26, 2014 at 9:58 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> One thing that might make it slightly less glitchy is choosing a different
> animation than default. Maybe something really simple, or no animation.
> Possibly could help.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/137#issuecomment-38693666
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by bepetersn** [comment]
Drop it now?

**Comment by eads** [comment]
Yeah, it's buggy and there's no upside to it. Instead of fixing the bugs in
a feature that isn't useful, just get rid of the feature that isn't useful.

On Wed, Mar 26, 2014 at 10:09 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> Drop it now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/137#issuecomment-38695215
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by GovInTrenches** [comment]
Dropping it is OK by me

-- 
Christopher Whitaker
Brigade Captain, City of Chicago
@CivicWhitaker

On March 26, 2014 at 10:11:44 AM, David Eads (notifications@github.com) wrote:

Yeah, it's buggy and there's no upside to it. Instead of fixing the bugs in
a feature that isn't useful, just get rid of the feature that isn't useful.

On Wed, Mar 26, 2014 at 10:09 AM, Brian Everett Peterson <
notifications@github.com> wrote:

> Drop it now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/137#issuecomment-38695215
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
Thanks Chris!

On Wed, Mar 26, 2014 at 10:15 AM, Christopher Whitaker <
notifications@github.com> wrote:

> Dropping it is OK by me
> 
> ## 
> 
> Christopher Whitaker
> Brigade Captain, City of Chicago
> @CivicWhitaker
> 
> On March 26, 2014 at 10:11:44 AM, David Eads (notifications@github.com)
> wrote:
> 
> Yeah, it's buggy and there's no upside to it. Instead of fixing the bugs
> in
> a feature that isn't useful, just get rid of the feature that isn't
> useful.
> 
> On Wed, Mar 26, 2014 at 10:09 AM, Brian Everett Peterson <
> notifications@github.com> wrote:
> 
> > Drop it now?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sc3/chicago-justice/issues/137#issuecomment-38695215>
> > .
> 
> ## 
> 
> David Eads - 773.354.2285
> News applications developer, Chicago Tribune (
> http://www.chicagotribune.com/news/data/)
> Founder, FreeGeek Chicago (http://freegeekchicago.org)
> 
> "Medical statistics will be our standard of measurement: we will weigh
> life
> for life and see where the dead lie thicker, among the workers or among
> the
> privileged." -- Rudolf Virchow
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/chicago-justice/issues/137#issuecomment-38695938
> .

## 

David Eads - 773.354.2285
News applications developer, Chicago Tribune (
http://www.chicagotribune.com/news/data/)
Founder, FreeGeek Chicago (http://freegeekchicago.org)

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by bepetersn** [comment]
Removed, but left in the infrastructure to add them.
