### ISSUE TITLE
Finish Arrest Tab

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#56]
Tab showing arrest data (none)

**Comment by danxoneil** [comment]
I think there's actually a lot of data we can point to under this. Isn't every mug shot website an example of this data?

**Comment by bepetersn** [comment]
See #57 and comments for some idea of the different parts of the site's components that you have to update to add a new tab.

**Comment by bepetersn** [comment]
Summary for the "Arrest" tab should look something like this for now:

This is a record of a person being taken into custody and charged with a crime. Typically one of two things happen after an arrest is made: if it is a misdemeanor, the arrest file is prepared for the State’s Attorney so that the case can be prosecuted in the Cook County Criminal Court. If it is a felony, the arrest file is prepared for the State’s Attorney so that they can review it and decide whether to pursue it as a felony in the Cook County Criminal Court. If no charges are filed by the State’s Attorney, there is no further action and no further data. An exception is in the case of a refusal by the State’s Attorney to press felony charges. Typically in this instance, the police are then given the opportunity to pursue the case as a misdemeanor.

**Comment by sarahelizabeth** [comment]
Added .html page, two .md files with summary content, made everything point in the right direction according to you list and it is still coming up with the wrong title, @bepetersn

**Comment by bepetersn** [comment]
We still need a photo for this page as well.
