### ISSUE TITLE
Create flowchart of the Criminal Justice System in Chicago as a whole 

### ISSUE THREAD

**Issue by GovInTrenches** [sc3/crime-punishment#58]
Create a "Criminal Justice System as a Whole" Tab with a graphic showing entire system. 

@sarahelizabeth - Can you create a chart in the same line that you did the prosecution chart? I can send you a photo of the chart

**Comment by sarahelizabeth** [comment]
@GovInTrenches Yes, can you please send it? Did you see the info graphic chart I sent you?

**Comment by GovInTrenches** [comment]
![image](https://f.cloud.github.com/assets/1302753/2153066/78b25e62-9422-11e3-9854-46672d7376b0.png)

**Comment by sarahelizabeth** [comment]
You got it

**Comment by GovInTrenches** [comment]
This is Tracy's discretion point chart that we can use for reference 

http://chicagojustice.org/research/long-form-reports/felony-sex-crime-case-processing-report-analysis-recommendations

**Comment by sarahelizabeth** [comment]
@GovInTrenches Just to clarify: you basically want me to make a much
simpler version of Tracy's chart, is that correct?

**Comment by danxoneil** [comment]
@sarahelizabeth: [that chart](http://chicagojustice.org/research/long-form-reports/felony-sex-crime-case-processing-report-analysis-recommendations/CJP_Sex_Crimes_Flow_Chart_Chicago-0.jpg/image_large) is more illustrative than instructive. Also: the chart only covers Felony Sex Crimes.

The idea is that we have a simple flowchart (like the dumb line chart I made in the image above) that allows us to schematically show the data model for crime and punishment in Chicago. I picture it also as a navigation method, so that clicking on the bolded item takes the user to that section, which explains the data fully.

Here's a better take on the content for the chart:

---

**Victimization**: this is the occurrence of an event that may be considered a crime. Typically one of two things happen after an event occurs: It may be reported via 911 or directly discovered by the police (“on view”), or it go completely unreported and unnoticed. If it is reported, a Call for Service is created. If it is unreported, there is no further action and no further data, save for the uncollected journal entries, phone calls to friends, or gossip on tech blogs about insider trading. 

**Call for Service**: this is a record of an incident that is reported to or discovered by the police. Typically one of two things happen after a Call for Service is generated: a report is filed or a report is not filed. The report may indicate that an arrest has been made or an investigation has begun. If there is no report, there is no further action and no further data.

**Report**: this is a record of the results of the Call for Service. Typically one of two things happen after a report is created: an arrest is made, and the report is prepared for  review by the State’s Attorney, or an investigation is pursued until an arrest is made. If no arrest is made, at some point the investigation is suspended and there is no further action and no further data.

**Arrest**: this is a record of a person being taken into custody and charged with a crime. Typically one of two things happen after an arrest is made: if it is a misdemeanor, the arrest file is prepared for the State’s Attorney so that the case can be prosecuted in the Cook County Criminal Court. If it is a felony, the arrest file is prepared for the State’s Attorney so that they can review it and decide whether to pursue it as a felony in the Cook County Criminal Court. If no charges are filed  by the State’s Attorney, there is no further action and no further data. An exception is in the case of a refusal by the State’s Attorney to press felony charges. Typically in this instance, the police are then given the opportunity to pursue the case as a misdemeanor.

**Charges**: this is a record of the formal charges brought against a person by the State’s Attorney. Typically one of two things happen after charges are filed: a person is incarcerated in Cook County Jail, or they make bail and await trial outside of jail.

**Jail**: this is a record of a person being incarcerated at Cook County Jail. Typically one of two things happen after a person is incarcerated in Cook County Jail: they are brought to trial in Cook County Criminal Court, or the charges are dropped.

**Court**: this is a record of the trial proceedings in Cook County Criminal Court for a person charged with a crime in the Cook County Criminal Court. Typically one of two things happen after a person goes on trial in Cook County Criminal Court: they are convicted or they are acquitted. If they are convicted, they may be incarcerated in prison. If they are acquitted, there is no further action and no further data.

**Prison**: this is a record of the disposition of a person after they are sentenced to prison as punishment for the crime for which they were convicted.

---

The idea here is to explain, in a flat, measured way, the linear process involved in crime and punishment in Chicago.

We seek to show exactly what data is generated in Chicago at very point, talk about what data is viewable to the public, and what data is not viewable. Then we try to point to other municipalities where the data is published so we can have a crisp, clear view of what we know and what we do not.

**Comment by GovInTrenches** [comment]
@bepetersn  - Let's get this content as the lead paragraph on all the pages.

**Comment by bepetersn** [comment]
Alright, I can do that.

@bepetersn https://github.com/bepetersn - Let's get this content as the
lead paragraph on all the pages.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/sc3/chicago-justice/issues/58#issuecomment-35102643
.

**Comment by sarahelizabeth** [comment]
@GovInTrenches  Have I shown you this yet? What are your thoughts on this? Do you want this to go on the homepage? Do you want the text you just sent me to be included for the graphic even though it is going up on all the pages individually?

![c p_graphic](https://f.cloud.github.com/assets/4665373/2178988/66b51734-9686-11e3-9187-1a4706ff26f5.jpg)

**Comment by GovInTrenches** [comment]
Looping @danxoneil in to look at this too.  To give some context, this is something that Sarah did for one of her classes. (Please correct if I'm mistaken) 

I like the flow and the breakdown of what the each element does within the system. We could build a link to the element's page as well. (And just put a short summary explaining how the case moves through the system and then link to the page that explains in detail what data is available, not available, ect)

**Comment by danxoneil** [comment]
@sarahelizabeth I think this chart is a great take on the criminal justice process.

The Crime and Punishment and Chicago project is less about process and more about data-- the inputs and outputs of the system. I think of the entire project as a data dictionary-- a flat, accurate, and super-detailed take on what records are generated at every step in the process.

What I had in mind was that the bolder words in my list would be the navigation for the entire site. So instead of "Report - Investigate - Prosecute - Jail - Court", the nav would be Victimization- Call for Service - Report - Arrest - Charges - Jail - Court - Prison.

As far as the flowchart, I was thinking simpler the better. More of a navigation elements.

Lemme know what you think!

**Comment by bepetersn** [comment]
So, then, it looks like we are still missing our project is still missing its "Prison" page. That will bring us up to a total of 8. 

If you look at the site right now, it's quite a mess (pictures disappeared?!). Nevertheless, you can see the main nav perfectly fine. With 7 pages up there, and a smaller font than we had before, it's looking a bit cramped. Does anyone have any thoughts about what we can do to make it look any better, but still hit so many points along the system?

There was an idea at one point to make the "home page" button more compact, sort of a styled logo (#45). Even doing that, I don't know how the site would look with so many nav elements.

**Comment by GovInTrenches** [comment]
What if we moved the social media links? We can always pin those to the bottom (or in the about page) 

We could also re-write to the nav to say "Crime & Punishment" to give us a bit more room. Since people will go to the main page and see Chicago on it, they'll know the site has a Chicago focus.

**Comment by sarahelizabeth** [comment]
I think what Brian is saying, and I totally agree with him, is that having 8 or 9 navigation tabs is visually distracting and confusing. Is there a way we can consolidate and perhaps have a secondary nav on a "police" page that includes victimization, call for service, and investigate.

**Comment by GovInTrenches** [comment]
Are ya'll available for a conference call or Google hangout real quick? (517-755-9266)

My instinct is that I'd rather lose the social media sharing buttons and add the 8th tab (and put recidivism into the prison tab) then trying to make a secondary nav page.

**Comment by bepetersn** [comment]
Sorry I didn't make myself available at that time. 

Actually, the social media icons already don't fit. (They could if we removed some of the padding or margin around them, I think, but not without feeling cramped.)  Compactifying the home button can only save so much space. No, I think the only conceivable way you can put 8 tabs up there is by taking up about the whole page width of a laptop, and just making the nav about twice as tall.

**Comment by bepetersn** [comment]
I told Chris earlier that maybe another way to do it would be to have a vertical rather than horizontal nav, like on the left side of the page. 

I don't really want to do that, however, until we are certain that this page structure doesn't work. The reason that I see Chris and Daniel wanting 8 pages is to try to better reflect the actual datasets and the agencies that are generating them, how that's happening. 

Still, we knew that the structure of the Criminal Justice System was complex from the very beginning. Even more complex than we are able to show with 8 pages. For instance, where does Charges data go in this 8-page schema? Or Contact Card data? Tracy would know better than I how many individual datasets there are, collected by how many agencies, but I think it's more than 8 for each of those. 

We probably have room to compromise underlying data structure with ease of explanation.

**Comment by GovInTrenches** [comment]
I'd like to see us try the horizontal w/ 8 and see how it looks. If we do it and it looks less than great, we can go back and switch to the vertical style nav bar.

**Comment by sarahelizabeth** [comment]
Hi Chris, I had a really good idea in terms of the nav. I hope to have it
finished by Saturday and I will email you a screenshot.

**Comment by bepetersn** [comment]
I'm going to close this issue for the moment, we can reopen it if the flowchart that is presently on the site is not what is desired.
