### ISSUE TITLE
Chart Templating

### ISSUE THREAD

**Issue by wilbertom** [sc3/crime-punishment#69]
I'm not sure if the chart changes on different tabs. The only change I see is the colored row. 

If this is the case then it should be templated. Or maybe made into a macro that takes a row as an argument and color the chart based on the argument.

**Comment by bepetersn** [comment]
Please figure out the _simplest_ possible solution to this problem, if you have any interest in it. 

It actually irks the heck out of me that we have this huge html-coded table in each template. I haven't devoted my attention to solving this lack of DRY-ness, because I'm trying not to be neurotic, and there are other important things to be done.

**Comment by wilbertom** [comment]
I got this one.

**Comment by wilbertom** [comment]
Hey @eads can you peer review this one? I can modify it to be better if needed.

**Comment by bepetersn** [comment]
This is on the backburner for now. Would be good to get this settled before the end of the project, though.

**Comment by sarahelizabeth** [comment]
We are getting rid of the chart so I am closing this.
